import * as vscode from 'vscode';
import { WorkItem } from '../models/workItem';

/**
 * Service for integrating with GitHub Copilot using VS Code Language Model API
 */
export class CopilotService {
  private static instance: CopilotService;
  private static readonly COPILOT_EXTENSION_ID = 'GitHub.copilot';
  private static readonly COPILOT_CHAT_EXTENSION_ID = 'GitHub.copilot-chat';

  private constructor() {
    // Private constructor for singleton pattern
  }

  public static getInstance(): CopilotService {
    if (!CopilotService.instance) {
      CopilotService.instance = new CopilotService();
    }
    return CopilotService.instance;
  }

  /**
   * Check if GitHub Copilot extension is installed
   */
  public isCopilotInstalled(): boolean {
    const copilotExtension = vscode.extensions.getExtension(CopilotService.COPILOT_EXTENSION_ID);
    const copilotChatExtension = vscode.extensions.getExtension(CopilotService.COPILOT_CHAT_EXTENSION_ID);

    return !!(copilotExtension || copilotChatExtension);
  }

  /**
   * Check if Copilot is available and the user has access
   */
  public async isCopilotAvailable(): Promise<boolean> {
    if (!this.isCopilotInstalled()) {
      return false;
    }

    try {
      // Check if Language Model API is available
      if (!vscode.lm || !vscode.lm.selectChatModels) {
        console.log('Language Model API not available');
        return false;
      }

      // Try to get available chat models
      const models = await vscode.lm.selectChatModels({
        vendor: 'copilot',
        family: 'gpt-4o'
      });

      return models.length > 0;
    } catch (error) {
      console.error('Error checking Copilot availability:', error);
      return false;
    }
  }

  /**
   * Get the Copilot extension object
   */
  private getCopilotExtension(): vscode.Extension<any> | undefined {
    return vscode.extensions.getExtension(CopilotService.COPILOT_EXTENSION_ID) ||
           vscode.extensions.getExtension(CopilotService.COPILOT_CHAT_EXTENSION_ID);
  }

  /**
   * Ensure Copilot extension is activated
   */
  private async ensureCopilotActivated(): Promise<boolean> {
    const extension = this.getCopilotExtension();

    if (!extension) {
      return false;
    }

    if (!extension.isActive) {
      try {
        await extension.activate();
        console.log('Copilot extension activated');
      } catch (error) {
        console.error('Failed to activate Copilot extension:', error);
        return false;
      }
    }

    return true;
  }

  /**
   * Generate a description for a work item using Copilot
   */
  public async generateDescription(workItem: WorkItem, existingDescription?: string): Promise<string> {
    // Ensure Copilot is available
    if (!await this.isCopilotAvailable()) {
      throw new Error('GitHub Copilot is not available. Please install and authenticate the GitHub Copilot extension.');
    }

    // Activate Copilot if needed
    if (!await this.ensureCopilotActivated()) {
      throw new Error('Failed to activate GitHub Copilot extension.');
    }

    const fields = workItem.fields;
    const title = fields['System.Title'];
    const workItemType = fields['System.WorkItemType'];
    const areaPath = fields['System.AreaPath'] || 'Unknown';
    const iterationPath = fields['System.IterationPath'] || 'Unknown';
    const tags = fields['System.Tags'] || 'None';

    // Build context-rich prompt
    const prompt = this.buildPrompt(title, workItemType, areaPath, iterationPath, tags, existingDescription);

    try {
      // Select Copilot chat model
      const models = await vscode.lm.selectChatModels({
        vendor: 'copilot',
        family: 'gpt-4o'
      });

      if (models.length === 0) {
        throw new Error('No Copilot models available');
      }

      const model = models[0];
      console.log(`Using Copilot model: ${model.id} (${model.vendor}/${model.family})`);

      // Create chat messages
      const messages = [
        vscode.LanguageModelChatMessage.User('You are a helpful assistant that writes clear, concise descriptions for Azure DevOps work items. Write 2-3 sentences describing what needs to be done and why. Be specific and actionable.'),
        vscode.LanguageModelChatMessage.User(prompt)
      ];

      // Send request to Copilot
      const response = await model.sendRequest(messages, {}, new vscode.CancellationTokenSource().token);

      // Collect the response
      let description = '';
      for await (const chunk of response.text) {
        description += chunk;
      }

      description = description.trim();

      if (!description) {
        throw new Error('No description generated by Copilot');
      }

      return description;
    } catch (error: any) {
      console.error('Copilot error details:', error);

      if (error.message?.includes('not available')) {
        throw new Error('GitHub Copilot is not available. Please ensure you have an active Copilot subscription and are signed in.');
      } else if (error.message?.includes('consent')) {
        throw new Error('User consent required. Please accept the GitHub Copilot terms in VS Code.');
      } else if (error.message) {
        throw new Error(`Copilot API error: ${error.message}`);
      } else {
        throw new Error(`Failed to generate description: ${String(error)}`);
      }
    }
  }

  /**
   * Build the prompt for Copilot
   */
  private buildPrompt(
    title: string,
    workItemType: string,
    areaPath: string,
    iterationPath: string,
    tags: string,
    existingDescription?: string
  ): string {
    if (existingDescription && existingDescription.trim() !== '') {
      return `Improve and refine the following description for this Azure DevOps work item:

Type: ${workItemType}
Title: ${title}
Area: ${areaPath}
Iteration: ${iterationPath}
Tags: ${tags}

Current Description:
${existingDescription}

Please improve this description by making it clearer, more concise, and more actionable. Keep it to 2-3 sentences. Maintain the core intent but enhance clarity and specificity.`;
    } else {
      return `Generate a concise 2-3 sentence description for this Azure DevOps work item:

Type: ${workItemType}
Title: ${title}
Area: ${areaPath}
Iteration: ${iterationPath}
Tags: ${tags}

Write a clear description of what needs to be done and why. Be specific and actionable.`;
    }
  }

  /**
   * Prompt user to install GitHub Copilot
   */
  public async promptToInstallCopilot(): Promise<boolean> {
    const action = await vscode.window.showInformationMessage(
      'GitHub Copilot is not installed. Would you like to install it?',
      'Install',
      'Cancel'
    );

    if (action !== 'Install') {
      return false;
    }

    try {
      // Open Copilot extension in marketplace
      await vscode.commands.executeCommand(
        'workbench.extensions.installExtension',
        CopilotService.COPILOT_EXTENSION_ID
      );

      vscode.window.showInformationMessage(
        'GitHub Copilot extension installation started. Please follow the authentication steps.'
      );

      return true;
    } catch (error) {
      console.error('Failed to install Copilot:', error);
      vscode.window.showErrorMessage('Failed to install GitHub Copilot extension.');
      return false;
    }
  }

  /**
   * Show Copilot status information
   */
  public async showCopilotStatus(): Promise<void> {
    const installed = this.isCopilotInstalled();
    const available = await this.isCopilotAvailable();

    let message = 'GitHub Copilot Status:\n\n';
    message += `Installed: ${installed ? '✓' : '✗'}\n`;
    message += `Available: ${available ? '✓' : '✗'}\n`;

    if (installed && !available) {
      message += '\nCopilot is installed but not available. Please ensure you have an active subscription and are signed in.';
    }

    vscode.window.showInformationMessage(message);
  }

  /**
   * Generate an implementation plan for a work item using Copilot
   */
  public async generateImplementationPlan(workItem: WorkItem): Promise<string> {
    if (!await this.isCopilotAvailable()) {
      throw new Error('GitHub Copilot is not available. Please install and authenticate the GitHub Copilot extension.');
    }

    if (!await this.ensureCopilotActivated()) {
      throw new Error('Failed to activate GitHub Copilot extension.');
    }

    const fields = workItem.fields;
    const title = fields['System.Title'];
    const workItemType = fields['System.WorkItemType'];
    const description = fields['System.Description'] || 'No description provided';
    const areaPath = fields['System.AreaPath'] || 'Unknown';
    const tags = fields['System.Tags'] || 'None';

    const prompt = `You are a senior software engineer helping to plan the implementation of a work item.

Work Item Details:
- Type: ${workItemType}
- Title: ${title}
- Description: ${description}
- Area: ${areaPath}
- Tags: ${tags}

Please create a detailed implementation plan that includes:

1. **Analysis**: Brief analysis of what needs to be done and any considerations
2. **Implementation Steps**: Numbered step-by-step plan with specific technical details
3. **Testing Strategy**: How to test the changes
4. **Potential Challenges**: Any gotchas or things to watch out for
5. **Estimated Complexity**: (Simple/Medium/Complex)

Make the plan actionable and specific. Use markdown formatting.`;

    try {
      const models = await vscode.lm.selectChatModels({
        vendor: 'copilot',
        family: 'gpt-4o'
      });

      if (models.length === 0) {
        throw new Error('No Copilot models available');
      }

      const model = models[0];
      const messages = [vscode.LanguageModelChatMessage.User(prompt)];
      const response = await model.sendRequest(messages, {}, new vscode.CancellationTokenSource().token);

      let plan = '';
      for await (const chunk of response.text) {
        plan += chunk;
      }

      plan = plan.trim();

      if (!plan) {
        throw new Error('No plan generated by Copilot');
      }

      return plan;
    } catch (error: any) {
      console.error('Copilot plan generation error:', error);

      if (error.message?.includes('not available')) {
        throw new Error('GitHub Copilot is not available. Please ensure you have an active Copilot subscription and are signed in.');
      } else if (error.message?.includes('consent')) {
        throw new Error('User consent required. Please accept the GitHub Copilot terms in VS Code.');
      } else if (error.message) {
        throw new Error(`Copilot API error: ${error.message}`);
      } else {
        throw new Error(`Failed to generate plan: ${String(error)}`);
      }
    }
  }

  /**
   * Generate suggestions for work item fields using Copilot
   */
  public async generateFieldSuggestions(
    workItemType: string,
    title: string,
    context?: string
  ): Promise<{ description?: string; acceptanceCriteria?: string; tasks?: string[] }> {
    if (!await this.isCopilotAvailable()) {
      throw new Error('GitHub Copilot is not available.');
    }

    if (!await this.ensureCopilotActivated()) {
      throw new Error('Failed to activate GitHub Copilot extension.');
    }

    const prompt = `For this Azure DevOps ${workItemType} titled "${title}"${context ? ` (Context: ${context})` : ''}, suggest:
1. A brief description (2-3 sentences)
2. Acceptance criteria (3-5 bullet points)
3. Potential subtasks or implementation steps (3-5 items)

Format your response as JSON with keys: description, acceptanceCriteria (array), tasks (array).`;

    try {
      const models = await vscode.lm.selectChatModels({
        vendor: 'copilot',
        family: 'gpt-4o'
      });

      if (models.length === 0) {
        throw new Error('No Copilot models available');
      }

      const model = models[0];
      const messages = [vscode.LanguageModelChatMessage.User(prompt)];
      const response = await model.sendRequest(messages, {}, new vscode.CancellationTokenSource().token);

      let result = '';
      for await (const chunk of response.text) {
        result += chunk;
      }

      // Try to parse JSON response
      try {
        const jsonMatch = result.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
      } catch (parseError) {
        console.error('Failed to parse Copilot response as JSON:', parseError);
      }

      // Fallback: return raw response as description
      return { description: result.trim() };
    } catch (error: any) {
      console.error('Error generating field suggestions:', error);
      throw new Error(`Failed to generate suggestions: ${error.message || String(error)}`);
    }
  }
}
